export const TABLE_COLUMNS = {
  matches: [
    { key: "user1", header: "User 1" },
    { key: "user2", header: "User 2" },
    { key: "status", header: "Status" },
    { key: "dateCreated", header: "Date Created" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  users: [
    { key: "name", header: "Name" },
    { key: "age", header: "Age" },
    { key: "married", header: "Married" },
    { key: "status", header: "Status" },
    { key: "city", header: "City" },
    { key: "email", header: "Email" },
    { key: "phone", header: "Phone" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  courses: [
    { key: "title", header: "Course Title" },
    { key: "category", header: "Category" },
    { key: "lessons", header: "Lessons" },
    { key: "status", header: "Status" },
    { key: "updatedAt", header: "Last Updated" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  events: [
    { key: "name", header: "Event Name" },
    { key: "location", header: "City, Country" },
    { key: "fee", header: "Fee" },
    { key: "status", header: "Status" },
    { key: "registrations", header: "Registrations" },
    { key: "eventDate", header: "Event Date" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  mentorship: [
    { key: "user1", header: "User 1" },
    { key: "user2", header: "User 2" },
    { key: "topic", header: "Topic" },
    { key: "status", header: "Status" },
    { key: "dateCreated", header: "Date Created" },
    { key: "preferredSlot", header: "Preferred slot" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  billing: [
    { key: "user", header: "User" },
    { key: "transactionId", header: "Transaction ID" },
    { key: "email", header: "Email" },
    { key: "paymentType", header: "Payment Type" },
    { key: "amount", header: "Amount" },
    { key: "status", header: "Status" },
    { key: "dateSubmitted", header: "Date Submitted" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  support: [
    { key: "ticketId", header: "Ticket ID" },
    { key: "user", header: "User" },
    { key: "issueType", header: "Issue Type" },
    { key: "status", header: "Status" },
    { key: "dateSubmitted", header: "Date Submitted" },
    { key: "actions", header: "Actions", align: "right" },
  ],
  members: [
    { key: "name", header: "Member Name" },
    { key: "email", header: "Email" },
    { key: "role", header: "Role" },
    { key: "status", header: "Status" },
    { key: "actions", header: "Actions", align: "right" },
  ],
};
